#!/usr/bin/env python3
import json
import os
import sys
import argparse

# Type mapping definitions
TYPE_MAP_CPP = {
    ("int", 1): "int8_t",
    ("int", 2): "int16_t",
    ("int", 4): "int32_t",
    ("int", 8): "int64_t",
    ("uint", 1): "uint8_t",
    ("uint", 2): "uint16_t",
    ("uint", 4): "uint32_t",
    ("uint", 8): "uint64_t",
    ("float", 4): "float",
    ("float", 8): "double",
    ("double", 8): "double",
    ("bool", 1): "bool",
    ("string", None): "std::string",
}

TYPE_MAP_CS = {
    ("int", 1): "sbyte",
    ("int", 2): "short",
    ("int", 4): "int",
    ("int", 8): "long",
    ("uint", 1): "byte",
    ("uint", 2): "ushort",
    ("uint", 4): "uint",
    ("uint", 8): "ulong",
    ("float", 4): "float",
    ("float", 8): "double",
    ("double", 8): "double",
    ("bool", 1): "bool",
    ("string", None): "string",
}

CS_DEFAULT_VALUES = {
    "sbyte": "0",
    "short": "0",
    "int": "0",
    "long": "0L",
    "byte": "0",
    "ushort": "0",
    "uint": "0U",
    "ulong": "0UL",
    "float": "0.0f",
    "double": "0.0",
    "bool": "false",
    "string": "string.Empty",
}

CPP_DEFAULT_VALUES = {
    "int8_t": "0",
    "int16_t": "0",
    "int32_t": "0",
    "int64_t": "0",
    "uint8_t": "0",
    "uint16_t": "0",
    "uint32_t": "0",
    "uint64_t": "0",
    "float": "0.0f",
    "double": "0.0",
    "bool": "false",
    "std::string": '""',
}

CS_BINARY_READER_METHODS = {
    "sbyte": "reader.ReadSByte()",
    "short": "reader.ReadInt16()",
    "int": "reader.ReadInt32()",
    "long": "reader.ReadInt64()",
    "byte": "reader.ReadByte()",
    "ushort": "reader.ReadUInt16()",
    "uint": "reader.ReadUInt32()",
    "ulong": "reader.ReadUInt64()",
    "float": "reader.ReadSingle()",
    "double": "reader.ReadDouble()",
    "bool": "reader.ReadBoolean()",
    "string": "PacketHelper.ReadPacketString(reader)",
}


def resolve_type(type_name, size, is_cs=False):
    key = (type_name, size if type_name != "string" else None)
    type_map = TYPE_MAP_CS if is_cs else TYPE_MAP_CPP
    if key in type_map:
        return type_map[key]
    if (type_name, 4) in type_map:
        return type_map[(type_name, 4)]
    return type_name


def generate_cpp(packets):
    code = """// Auto-generated by packet_gen.py. DO NOT EDIT!
#ifndef __PACKETS_GENERATED_H__
#define __PACKETS_GENERATED_H__

#include <cstdint>
#include <string>
#include <vector>
#include <span>
#include <cstring>
#include <stdexcept>
#include "packet.h"

namespace Packet
{

class Reader
{
public:
    Reader(std::span<const std::byte> data) : data_(data), offset_(0) {}

    template <typename T>
    T read()
    {
        static_assert(std::is_trivially_copyable_v<T>, "Type must be trivially copyable");
        if (offset_ + sizeof(T) > data_.size())
            throw std::runtime_error("Packet buffer underflow");
        T val;
        std::memcpy(&val, data_.data() + offset_, sizeof(T));
        offset_ += sizeof(T);
        return val;
    }

    std::string read_string()
    {
        uint16_t len = read<uint16_t>();
        if (offset_ + len > data_.size())
            throw std::runtime_error("Packet string underflow");
        std::string str(reinterpret_cast<const char*>(data_.data() + offset_), len);
        offset_ += len;
        return str;
    }

    size_t remaining() const { return data_.size() - offset_; }

private:
    std::span<const std::byte> data_;
    size_t offset_ = 0;
};

class Writer
{
public:
    template <typename T>
    void write(const T& val)
    {
        static_assert(std::is_trivially_copyable_v<T>, "Type must be trivially copyable");
        const auto* ptr = reinterpret_cast<const std::byte*>(&val);
        buffer_.insert(buffer_.end(), ptr, ptr + sizeof(T));
    }

    void write_string(const std::string& str)
    {
        write<uint16_t>(static_cast<uint16_t>(str.size()));
        const auto* ptr = reinterpret_cast<const std::byte*>(str.data());
        buffer_.insert(buffer_.end(), ptr, ptr + str.size());
    }

    void write_raw(const std::vector<std::byte>& raw)
    {
        buffer_.insert(buffer_.end(), raw.begin(), raw.end());
    }

    const std::vector<std::byte>& buffer() const { return buffer_; }
    std::vector<std::byte>& buffer() { return buffer_; }

private:
    std::vector<std::byte> buffer_;
};

"""

    for pkt in packets:
        name = pkt["name"]
        pkt_id = pkt["id"]

        for side, prefix, alias_suffix in [("client", "C2S_", "ClientPacket"), ("server", "S2C_", "ServerPacket")]:
            if side not in pkt:
                continue

            fields = pkt[side]
            struct_name = f"{prefix}{name}"
            alias_name = f"{name}{alias_suffix}"

            code += f"struct {struct_name}\n{{\n"
            code += f"    static constexpr uint32_t ID = {pkt_id};\n\n"

            # Fields
            for fname, finfo in fields.items():
                cpp_type = resolve_type(finfo.get("type"), finfo.get("size"), is_cs=False)
                default_val = CPP_DEFAULT_VALUES.get(cpp_type, "")
                if default_val:
                    code += f"    {cpp_type} {fname} = {default_val};\n"
                else:
                    code += f"    {cpp_type} {fname};\n"
            code += "\n"

            # Deserialize
            if not fields:
                code += f"    static {struct_name} deserialize([[maybe_unused]] std::span<const std::byte> payload)\n    {{\n"
                code += f"        return {struct_name}{{}};\n"
                code += f"    }}\n\n"
            else:
                code += f"    static {struct_name} deserialize(std::span<const std::byte> payload)\n    {{\n"
                code += f"        Reader reader(payload);\n"
                code += f"        {struct_name} packet;\n"
                for fname, finfo in fields.items():
                    cpp_type = resolve_type(finfo.get("type"), finfo.get("size"), is_cs=False)
                    if cpp_type == "std::string":
                        code += f"        packet.{fname} = reader.read_string();\n"
                    else:
                        code += f"        packet.{fname} = reader.read<{cpp_type}>();\n"
                code += f"        return packet;\n"
                code += f"    }}\n\n"

            # Serialize
            if not fields:
                code += f"    std::vector<std::byte> serialize() const\n    {{\n"
                code += f"        PacketHeader header;\n"
                code += f"        header.packet_id = ID;\n"
                code += f"        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader));\n\n"
                code += f"        Writer writer;\n"
                code += f"        writer.write(header);\n"
                code += f"        return writer.buffer();\n"
                code += f"    }}\n"
            else:
                code += f"    std::vector<std::byte> serialize() const\n    {{\n"
                code += f"        Writer body;\n"
                for fname, finfo in fields.items():
                    cpp_type = resolve_type(finfo.get("type"), finfo.get("size"), is_cs=False)
                    if cpp_type == "std::string":
                        code += f"        body.write_string({fname});\n"
                    else:
                        code += f"        body.write<{cpp_type}>({fname});\n"
                code += f"\n        PacketHeader header;\n"
                code += f"        header.packet_id = ID;\n"
                code += f"        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader) + body.buffer().size());\n\n"
                code += f"        Writer writer;\n"
                code += f"        writer.write(header);\n"
                code += f"        writer.write_raw(body.buffer());\n"
                code += f"        return writer.buffer();\n"
                code += f"    }}\n"

            code += f"}};\n"
            code += f"using {alias_name} = {struct_name};\n\n"

    code += "} // namespace Packet\n\n"
    code += "#endif // __PACKETS_GENERATED_H__\n"
    return code


def generate_cs(packets):
    code = """// Auto-generated by packet_gen.py. DO NOT EDIT!
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

namespace Blocks.Network
{
    public enum PacketId : uint
    {
"""
    for pkt in packets:
        code += f"        {pkt['name']} = {pkt['id']},\n"
    code += """    }

    public static class PacketHelper
    {
        public static string ReadPacketString(BinaryReader reader)
        {
            ushort len = reader.ReadUInt16();
            byte[] bytes = reader.ReadBytes(len);
            return Encoding.UTF8.GetString(bytes);
        }

        public static void WritePacketString(BinaryWriter writer, string str)
        {
            str ??= string.Empty;
            byte[] bytes = Encoding.UTF8.GetBytes(str);
            writer.Write((ushort)bytes.Length);
            writer.Write(bytes);
        }
    }
"""

    for pkt in packets:
        name = pkt["name"]
        pkt_id = pkt["id"]

        for side, prefix, alias_suffix in [("client", "C2S_", "ClientPacket"), ("server", "S2C_", "ServerPacket")]:
            if side not in pkt:
                continue

            fields = pkt[side]
            class_name = f"{prefix}{name}"

            code += f"""
    public class {class_name}
    {{
        public const uint ID = {pkt_id};

"""
            # Fields
            for fname, finfo in fields.items():
                cs_type = resolve_type(finfo.get("type"), finfo.get("size"), is_cs=True)
                default_val = CS_DEFAULT_VALUES.get(cs_type, "default")
                code += f"        public {cs_type} {fname} = {default_val};\n"
            code += "\n"

            # Serialize
            if not fields:
                code += f"""        public byte[] Serialize()
        {{
            uint packetSize = 8;
            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            return packetMs.ToArray();
        }}

        public static {class_name} Deserialize(BinaryReader reader)
        {{
            return new {class_name}();
        }}

        public static {class_name} Deserialize(byte[] payload, int offset = 0, int length = -1)
        {{
            return new {class_name}();
        }}
    }}
"""
            else:
                code += f"""        public byte[] Serialize()
        {{
            using var bodyMs = new MemoryStream();
            using var bodyWriter = new BinaryWriter(bodyMs);
"""
                for fname, finfo in fields.items():
                    cs_type = resolve_type(finfo.get("type"), finfo.get("size"), is_cs=True)
                    if cs_type == "string":
                        code += f"            PacketHelper.WritePacketString(bodyWriter, {fname});\n"
                    else:
                        code += f"            bodyWriter.Write({fname});\n"

                code += f"""
            byte[] bodyBytes = bodyMs.ToArray();
            uint packetSize = (uint)(8 + bodyBytes.Length);

            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            packetWriter.Write(bodyBytes);
            return packetMs.ToArray();
        }}

        public static {class_name} Deserialize(BinaryReader reader)
        {{
            var packet = new {class_name}();
"""
                for fname, finfo in fields.items():
                    cs_type = resolve_type(finfo.get("type"), finfo.get("size"), is_cs=True)
                    read_expr = CS_BINARY_READER_METHODS.get(cs_type, f"reader.{cs_type}")
                    code += f"            packet.{fname} = {read_expr};\n"

                code += f"""            return packet;
        }}

        public static {class_name} Deserialize(byte[] payload, int offset = 0, int length = -1)
        {{
            if (length < 0) length = payload.Length - offset;
            using var ms = new MemoryStream(payload, offset, length);
            using var reader = new BinaryReader(ms);
            return Deserialize(reader);
        }}
    }}
"""

    code += "}\n"
    return code


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    default_json = os.path.join(script_dir, "packet.json")
    default_cpp_out = os.path.join(script_dir, "packets_generated.h")
    default_cs_out = os.path.join(script_dir, "PacketGenerated.cs")

    parser = argparse.ArgumentParser(description="Generate C++ and C# packet code from packet.json")
    parser.add_argument("--json", default=default_json, help="Path to packet.json")
    parser.add_argument("--cpp-out", default=default_cpp_out, help="Output C++ header file path")
    parser.add_argument("--cs-out", default=default_cs_out, help="Output C# source file path")

    args = parser.parse_args()

    if not os.path.exists(args.json):
        print(f"Error: JSON file not found: {args.json}", file=sys.stderr)
        sys.exit(1)

    with open(args.json, "r", encoding="utf-8") as f:
        data = json.load(f)

    packets = data.get("packets", [])
    print(f"Loaded {len(packets)} packet definitions from {args.json}")

    # Generate C++
    cpp_code = generate_cpp(packets)
    os.makedirs(os.path.dirname(os.path.abspath(args.cpp_out)), exist_ok=True)
    with open(args.cpp_out, "w", encoding="utf-8") as f:
        f.write(cpp_code)
    print(f"Generated C++: {args.cpp_out}")

    # Generate C#
    cs_code = generate_cs(packets)
    os.makedirs(os.path.dirname(os.path.abspath(args.cs_out)), exist_ok=True)
    with open(args.cs_out, "w", encoding="utf-8") as f:
        f.write(cs_code)
    print(f"Generated C#:  {args.cs_out}")

    print("Code generation completed successfully!")


if __name__ == "__main__":
    main()
